### ISSUE TITLE
Uppercase letters in ami_password became lowercase

### ISSUE THREAD

**Issue by TerehinAV** [davies147/astmanproxy#12]
Hi!
If my ami_password containts uppercase letters, when I try to start astmanproxy, it received "Authentication failed  error". 
Astmanproxy replaces all uppercase letters of the password with lowercase:

in astmanproxy.conf:
host = AMI_HOST,AMI_PORT,ami_user,MyAmiPassword,off,off

in log:

Oct 15 16:24:08: asterisk@AMI_HOST: Connecting (u=ami_user, p=myamipassword, ssl=off)

**Comment by davies147** [comment]
I have pushed a commit to the WIP branch which should fix this - If you could try that and let me know?

**Comment by TerehinAV** [comment]
I switched to WIP branch, pulled updates and checked for changes:
 if ( ccount != 2 && ccount != 3 )
                        *s = tolower(*s);
I rebuilt and still the password becomes lowercase :(

```
Oct 15 20:21:13: asterisk@AMI_HOST: Connecting (u=ami_user, p=1znfke, ssl=off)
Oct 15 20:21:13: Listening for connections
Oct 15 20:21:13: returning ast_connect with 5
Oct 15 20:21:13: Transmitting standard block of 4 lines, fd 5
Oct 15 20:21:13: asterisk@AMI_HOST: attempting read...
Oct 15 20:21:13: get_input returned line 1, res 0,
Oct 15 20:21:13: get_input returned line 1, res 1, Asterisk Call Manager/2.10.4
Oct 15 20:21:14: get_input returned line 2, res 0,
Oct 15 20:21:14: get_input returned line 2, res 1, Response: Error
Oct 15 20:21:14: get_input returned line 3, res 1, Message: Authentication failed
Oct 15 20:21:14: get_input returned line 4, res -1,
Oct 15 20:21:14: Read error -1 getting line
Oct 15 20:21:14: Returning standard block of 3 lines, res -1
```

**Comment by davies147** [comment]
Okay - I will test this a bit better today.

**Comment by davies147** [comment]
Wow, the original code was very persistent in using `to_lower` :-)

I have updated the WIP branch if you care to pull the latest and test it?

**Comment by TerehinAV** [comment]
I just checked, now it works with any letters :) thank you!

**Comment by davies147** [comment]
Thanks for the fast feedback.

**Comment by TerehinAV** [comment]
Something goes wrong, Requests stop working with connection error ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by TerehinAV** [comment]
No, It's not about PBX, I switched to master and return my ami_pass to lowercase letters and my requests works. Something broke in the WIP branch

**Comment by davies147** [comment]
Can you provide a debug trace of when it fails. Perhaps on a new issue#

**Comment by TerehinAV** [comment]
```
Oct 16 13:00:00: asterisk@amy_host got: Asterisk Call Manager/2.10.4
Oct 16 13:00:00: asterisk@amy_host got: Response: Success
Oct 16 13:00:00: asterisk@amy_host got: Message: Authentication accepted
Oct 16 13:00:00: asterisk@amy_host: connected successfully!
Oct 16 13:00:00: asterisk@amy_host: attempting read...



Oct 16 13:00:09: is_encrypted: 0
Oct 16 13:00:09: Connection received from my_host
Oct 16 13:00:09: Set my_host input format to http
Oct 16 13:00:09: Set my_host output format to standard
[New Thread 0x7fffefbfe700 (LWP 1986)]
Oct 16 13:00:14: Connection closed: my_host
Oct 16 13:00:14: Freed entire stack.
Oct 16 13:00:14: --- exiting session_do thread ---
[Thread 0x7fffefbfe700 (LWP 1986) exited]
```
